### ISSUE TITLE
[css-properties-values-api] Mass property registration

### ISSUE THREAD

**Issue by LeaVerou** [w3c/css-houdini-drafts#1058]
Twitter thread: https://twitter.com/James0x57/status/1467601715067342853

It's rather common to register a number of properties with the same descriptors. E.g. most `<integer>`, `<number>` or `<length>` properties are registered to have an initial value of `0` and most properties are registered to have `inherits: true`. So, the multiple `@property` rules can get quite repetitive. For a particularly egregious example of this, look [here](https://github.com/propjockey/css-conways-game-of-life/blob/main/game-of-life.css#L140).

This proposal is about two things:
## `@property` should be able to define multiple properties with the same descriptors by just comma-separating them.

This is such low hanging fruit, that the MDN and web.dev docs on `@property` [originally included it](https://github.com/mdn/content/issues/5830) even though it was never a thing on the CSS side! 

It should also be pretty easy to do, if it's just a parse time shortcut that is expanded into multiple rules for the CSSOM.

We could even define them to cascade, like so:

```css
@property --number, --scale {
	syntax: "<number>";
	initial-value: 0;
	inherits: true;
}

@property --scale {
	initial-value: 1;
}
```

`CSS.registerProperty()` does not need to change, since if you're in JS-land, you can just loop anyway.

## Authors should be able to register entire namespaces of properties by using a wildcard at the end.

Something like this would help condense the [4000 lines of property registrations here](https://github.com/propjockey/css-conways-game-of-life/blob/main/game-of-life.css#L140) to just one. Admittedly, this is not a realistic example of regular CSS, but I've definitely come across more real cases of duplication that could be eliminated this way.

Another use case is utility registered properties like `--int-*`, `--length-*` etc [see tweet by @propjockey](https://twitter.com/James0x57/status/1467646389148688384).

@tabatkins said [he thinks it is feasible](https://twitter.com/tabatkins/status/1467686598649073667).

These would also need to be combinable, to deal with potential conflicts:

```css
@property --int-* {
	syntax: "<number>";
	initial-value: 0;
	inherits: true;
}

@property --int-foo-* {
	initial-value: 1;
}

@property --int-foo-bar {
	initial-value: 2;
}
```

Since `<dashed-ident>` does not permit `*`, I suppose we'd need to define a new token, `<dashed-ident-group>` 
`CSS.registerProperty()` could just accept these tokens under `name`, to minimize API changes, or we could do something more fancy on the JS side.

CSSOM wise this cannot really be expanded at parse time, since the set is infinite. Perhaps there should be some read-only boolean for authors to check if this is a group without having to do `rule.name.endsWith("*")`, but that's a minor point.

**Comment by tabatkins** [comment]
The first one (multiple comma-separated names in the registration) we should definitely do, no question. Such an obvious improvement.

The second (wildcard registration) is something I support if it's feasible on implementations. No need to get fancy with the API, it'll just be a new name form; an `<ident-token>` followed by a "*" `<delim-token>`.

Your idea of combining them if multiple apply is interesting, but new to the API; currently each definition is independent, and will override each other if they collide names. I'd assumed we'd use longest-prefix-match semantics, so in your example `--int-foo-1` would use the `@property --int-foo-*` block, but not the `@property --int-*` one.

**Comment by tabatkins** [comment]
Oh, but:

> It should also be pretty easy to do, if it's just a parse time shortcut that is expanded into multiple rules for the CSSOM.

It shouldn't be expanded into multiple rules. We can either make the .name property an array now, hoping the compat is fine, or keep it a string that might be comma-delimited.

**Comment by SebastianZ** [comment]
> make the .name property an array now, hoping the compat is fine, or keep it a string that might be comma-delimited.

Then it should probably also be renamed to `names` to indicate that it can hold multiple property names, if there are no compat issues.

Sebastian

**Comment by bramus** [comment]
Got sent a similar request via Twitter: https://twitter.com/LukyVJ/status/1627624292484542467

With `@property` shipping in browsers other than Chrome soon, and more people using it, I predict more similar requests in the near future.

**Comment by Crissov** [comment]
For at least 4 years now, everybody has agreed the syntax for [`@property`](](https://drafts.csswg.org/css-variables-2/#typedef-custom-property-name) should be :
~~~~ css
@property <custom-property-name># {
  <declaration-list>
}
~~~~
but in the current draft it still lacks that `#`.

**Comment by LeaVerou** [comment]
> For at least 4 years now, everybody has agreed the syntax for [`@property`](]([drafts.csswg.org/css-variables-2#typedef-custom-property-name](https://drafts.csswg.org/css-variables-2/#typedef-custom-property-name)) should be :
> 
> @property <custom-property-name># {
>   <declaration-list>
> }
> but in the current draft it still lacks that `#`.

If you can point to a resolution for the "everybody has agreed" I will commit the change!

**Comment by andruud** [comment]
There is another proposal here: https://github.com/w3c/csswg-drafts/issues/7523#issuecomment-1683831209 (based on Tab's post immediately before):

```css
@property {
  syntax: "<length>";
  inherits: false;
  initial-value: 2147483647px;
  --width: initial; /* 2147483647px */
  --height: initial; /* 2147483647px */
  --depth: 0px;
}
```

And/or we could imagine that a hypothetical `initial()` function is allowed here, to be able to express an initial value in terms of other initial values:

```css
@property {
  syntax: "<length>";
  inherits: false;
  --one: 1px;
  --two: 2px;
  --width: initial(--one);
  --height: initial(--two);
  --foo: calc(initial(--one) + initial(--two));
}
```

That would require a novel concept of "computing" an _initial_ value, but that should be possible as long as everything is [computationally independent](https://drafts.css-houdini.org/css-properties-values-api-1/#computationally-independent) otherwise.

---

Mass registration with wildcards: so ... `@property --int-*` is basically something like a "selector" that "matches" custom property names on that form? I'm not sure if it's wise to bake that much (potentially expensive) complexity into the the computed value process. Hopefully we can consider other ways to solve the use-cases this would be needed for. For example, custom functions/`if()` could help for some of them?
