### ISSUE TITLE
[css-properties-values-api] `initial-value` for `*` with arbitrary substitution values

### ISSUE THREAD

**Issue by cdoublev** [w3c/css-houdini-drafts#1120]
If I understand the spec correctly, [`initial-value`](https://drafts.css-houdini.org/css-properties-values-api-1/#initial-value-descriptor) does not require to be validated when `syntax` is `*`.

But in Chrome, given the CSS rules below:

  - the first rule is valid: `initial-value: var(1)` is discarded
  - the second rule is invalid

```css
@property --p1 {
  inherits: false;
  syntax: "*";
  initial-value: green;
  initial-value: var(1);
}
@property --p2 {
  inherits: false;
  syntax: "*";
  initial-value: green;
  initial-value: var(--initial);
}
```

I am completely confused by the parse result in Chrome. Anyway, should `initial-value` be invalid when it includes an arbitrary substitution value?
