### ISSUE TITLE
[css-properties-values] Example 1 seems to do the same thing twice

### ISSUE THREAD

**Issue by jakearchibald** [w3c/css-houdini-drafts#38]
https://drafts.css-houdini.org/css-properties-values-api/#example-1

I found this bit confusing:

```css
* {
    transform: translate(var(--translate-x), var(--translate-y)) rotate(var(--rotate)) scale(var(--scale-x), var(--scale-y));
}
```

…is it meant to be there? It seems to be doing the same job as `registerApplyHook`.
