### ISSUE TITLE
[css-paint-api] Rename paint(name, args) to paint-name(args)

### ISSUE THREAD

**Issue by LeaVerou** [w3c/css-houdini-drafts#751]
The way the Paint API currently works is that it gives authors a `paint()` function, whose first argument is an `<ident>` for the name of painting operation.

However, putting the name of painting in the function call has several benefits:

- It makes the call easier to read, since the paint name is not really an argument, it's conceptually part of the function.
- It makes web developers feel that they are creating an actual CSS function, instead of merely extending an existing function.
- It actually reads nicer, since "paint" combines nicely with the name of what is being painted. There is also more prominent visual separation between the paint operation and the arguments, making it easier to read and process. 

Compare (examples from the spec):

```css
.logo { background-image: paint(company-logo); }
.chat-bubble { background-image: paint(chat-bubble, blue); }
```

vs:

```css
.logo { background-image: paint-company-logo(); }
.chat-bubble { background-image: paint-chat-bubble(blue); }
```

Isn't the latter much easier to read? Doesn't it immediately communicate what it's doing?

Also, as a polyfill author it is much easier to explain to my users that my script adds a new `paint-rainbow()` function that they use with x, y, z arguments, than to explain that they have to use this generic `paint()` function, where the first argument is fixed to `rainbow` and the rest are the actual arguments they provide. 

I recall mentioning this in person to some Houdini folks ages ago, and they agreed, but I never made an issue so I guess it was forgotten.
