### ISSUE TITLE
[css-properties-values-api] Need to resolve computation/animation/substitution order for typed properties

### ISSUE THREAD

**Issue by shans** [w3c/css-houdini-drafts#79]
This currently works:
```css
.foo {
  width: var(--a);
  transition: width 1s;
}

.foo:hover {
  width: var(--b);
}
```

It works because custom property substitution happens before computation or animation:

Inheritance
CP Substitution
Computation
Transitions/Animations

However, once we have typed properties then this will fail using the above order:
```css
.foo {
  width: var(--a);
  transition: --a 1s;
  --a: 100px;
}

.foo:hover {
  --a: 200px;
}
```

By the time the animation kicks off, animation has already happened.

The solution is probably to add some additional steps:

Inheritance
CP Computation
CP Animation
CP Substitution
Computation
Transitions/Animations
